branches:
  only:
  - development
language: python
cache: pip
python:
- 3.4
- 3.5
- 3.6
- 3.7-dev
env:
- DJANGO='django>=1.8,<1.9'
- DJANGO='django>=1.10,<1.11'
- DJANGO='django>=1.11,<1.12'
- DJANGO=https://github.com/django/django/archive/master.tar.gz
matrix:
  exclude:
  - python: 3.6
    env: DJANGO='django>=1.8,<1.9'
  - python: 3.6
    env: DJANGO='django>=1.10,<1.11'
  - python: 3.7-dev
    env: DJANGO='django>=1.8,<1.9'
  - python: 3.7-dev
    env: DJANGO='django>=1.10,<1.11'
  allow_failures:
  - python: 3.4
    env: DJANGO=https://github.com/django/django/archive/master.tar.gz
  - python: 3.5
    env: DJANGO=https://github.com/django/django/archive/master.tar.gz
  - python: 3.6
    env: DJANGO=https://github.com/django/django/archive/master.tar.gz
  - python: 3.7-dev
    env: DJANGO='django>=1.11,<1.12'
  - python: 3.7-dev
    env: DJANGO=https://github.com/django/django/archive/master.tar.gz
install:
- pip install -r requirements.txt
- pip install "$DJANGO"
- pip install codecov
- ./setup.py develop
before_script:
- if [[ `python -V | grep -c -e 3.6` -eq 1 && "$DJANGO" == 'django>=1.11,<1.12' ]]; then ./setup.py check --strict --metadata --restructuredtext ; fi
- if [[ `python -V | grep -c -e 3.6` -eq 1 && "$DJANGO" == 'django>=1.11,<1.12' ]]; then check-manifest . ; fi
- if [[ `python -V | grep -c -e 3.6` -eq 1 && "$DJANGO" == 'django>=1.11,<1.12' ]]; then flake8 src tests setup.py runtests.py ; fi
- if [[ `python -V | grep -c -e 3.6` -eq 1 && "$DJANGO" == 'django>=1.11,<1.12' ]]; then isort --verbose --check-only --diff --recursive src tests setup.py runtests.py ; fi
- if [[ `python -V | grep -c -e 3.6` -eq 1 && "$DJANGO" == 'django>=1.11,<1.12' ]]; then pylint --rcfile=.pylintrc -d fixme src tests setup.py runtests.py ; fi
script:
# do not use setup.py test with coverage; missing files omitted entirely
- coverage run runtests.py
after_success:
# coverage is run in parallel, so it is necessary to combine the reports
# Note that this is only for our benefit: codecov handles this itself
# https://github.com/codecov/codecov-python/issues/72
- coverage combine --append && coverage report && codecov
after_script:
- pip uninstall -y django  # to remove from cache
